IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS	WHERE TABLE_NAME = 'ProxymedResponse' AND COLUMN_NAME = 'SecondaryIdentifier')
BEGIN
	ALTER TABLE dbo.ProxymedResponse
	ADD SecondaryIdentifier VARCHAR(32) NULL 
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS	WHERE TABLE_NAME = 'GatewayEDIResponse' AND COLUMN_NAME = 'SecondaryIdentifier')
BEGIN
	ALTER TABLE dbo.GatewayEDIResponse
	ADD SecondaryIdentifier VARCHAR(32) NULL 
END
