UPDATE STATISTICS dbo.Claim WITH FULLSCAN
UPDATE STATISTICS dbo.ClaimAccounting WITH FULLSCAN
UPDATE STATISTICS dbo.ClaimAccounting_Billings WITH FULLSCAN
UPDATE STATISTICS dbo.Practice WITH FULLSCAN