
ALTER TABLE Bill_Statement DROP CONSTRAINT FK_BillStatement_BillBatch

ALTER TABLE Bill_EDI DROP CONSTRAINT FK_BillEDI_BillBatch

ALTER TABLE Bill_HCFA DROP CONSTRAINT FK_BillHCFA_BillBatch

ALTER TABLE Bill DROP CONSTRAINT FK_Bill_BillBatch

ALTER TABLE BillBatch DROP CONSTRAINT PK_BillBatch

CREATE CLUSTERED INDEX CI_BillBatch_PracticeID_BillBatchTypeCode_BillBatchID
ON BillBatch(PracticeID, BillBatchTypeCode, BillBatchID)

ALTER TABLE BillBatch ADD CONSTRAINT PK_BillBatch 
PRIMARY KEY NONCLUSTERED (BillBatchID)

ALTER TABLE Bill_Statement ADD CONSTRAINT FK_Bill_Statement_BillBatchID
FOREIGN KEY (BillBatchID) REFERENCES BillBatch(BillBatchID)
ON DELETE NO ACTION ON UPDATE NO ACTION

ALTER TABLE Bill_EDI ADD CONSTRAINT FK_Bill_EDI_BillBatchID
FOREIGN KEY (BillBatchID) REFERENCES BillBatch(BillBatchID)
ON DELETE NO ACTION ON UPDATE NO ACTION

ALTER TABLE Bill_HCFA ADD CONSTRAINT FK_Bill_HCFA_BillBatchID
FOREIGN KEY (BillBatchID) REFERENCES BillBatch(BillBatchID)
ON DELETE NO ACTION ON UPDATE NO ACTION

ALTER TABLE Bill ADD CONSTRAINT FK_Bill_BillBatchID
FOREIGN KEY (BillBatchID) REFERENCES BillBatch(BillBatchID)
ON DELETE NO ACTION ON UPDATE NO ACTION

CREATE NONCLUSTERED INDEX IX_BilLBatch_ConfirmedDate
ON BillBatch(ConfirmedDate)

CREATE NONCLUSTERED INDEX IX_Bill_EDI_BillBatchID
ON BIll_EDI(BillBatchID)

CREATE NONCLUSTERED INDEX IX_Bill_EDI_RepresentativeClaimID
ON BIll_EDI(RepresentativeClaimID)

CREATE NONCLUSTERED INDEX IX_Bill_EDI_PayerInsurancePolicyID
ON BIll_EDI(PayerInsurancePolicyID)

CREATE NONCLUSTERED INDEX IX_Bill_EDI_OtherPayerInsurancePolicyID
ON BIll_EDI(OtherPayerInsurancePolicyID)

CREATE NONCLUSTERED INDEX IX_Bill_HCFA_BillBatchID
ON BIll_HCFA(BillBatchID)

CREATE NONCLUSTERED INDEX IX_Bill_HCFA_RepresentativeClaimID
ON BIll_HCFA(RepresentativeClaimID)

CREATE NONCLUSTERED INDEX IX_Bill_HCFA_PayerInsurancePolicyID
ON BIll_HCFA(PayerInsurancePolicyID)

CREATE NONCLUSTERED INDEX IX_Bill_HCFA_OtherPayerInsurancePolicyID
ON BIll_HCFA(OtherPayerInsurancePolicyID)

CREATE NONCLUSTERED INDEX IX_BillClaim_BillBatchTypeCode_ClaimID
ON BillClaim (BillBatchTypeCode,ClaimID)

DBCC DBREINDEX(BillBatch)
DBCC DBREINDEX(Bill_EDI)
DBCC DBREINDEX(Bill_HCFA)
DBCC DBREINDEX(BillClaim)

UPDATE STATISTICS BillBatch
UPDATE STATISTICS Bill_EDI
UPDATE STATISTICS Bill_HCFA
UPDATE STATISTICS BillClaim

GO

ALTER TABLE InsuranceCompany DROP CONSTRAINT [DF_InsuranceCompany_InsuranceProgramCode]

ALTER TABLE [dbo].[InsuranceCompany] ADD 
	CONSTRAINT [DF_InsuranceCompany_InsuranceProgramCode] DEFAULT ('CI') FOR [InsuranceProgramCode]
GO
