IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Numbers' AND TABLE_TYPE = 'BASE TABLE')
BEGIN
	DROP TABLE dbo.Numbers
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'Numbers')
BEGIN
	DROP VIEW Numbers	
END
GO

CREATE VIEW Numbers
WITH SCHEMABINDING
AS
	WITH Int1(z) AS (SELECT 0 UNION ALL SELECT 0)
		, Int2(z) AS (SELECT 0 FROM Int1 a CROSS JOIN Int1 b)
		, Int4(z) AS (SELECT 0 FROM Int2 a CROSS JOIN Int2 b)
		, Int8(z) AS (SELECT 0 FROM Int4 a CROSS JOIN Int4 b)
		, Int16(z) AS (SELECT 0 FROM Int8 a CROSS JOIN Int8 b)
		, Int32(z) AS (SELECT TOP 2147483647 0 FROM Int16 a CROSS JOIN Int16 b)
	SELECT ROW_NUMBER() OVER (ORDER BY z) AS Number
	FROM Int32

