BEGIN TRANSACTION
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
UPDATE Customer SET Metrics=1 WHERE Metrics IS NULL
ALTER TABLE customer DROP CONSTRAINT DF_Customer_Metrics;
ALTER TABLE dbo.Customer ALTER COLUMN Metrics INTEGER NOT NULL 
ALTER TABLE dbo.Customer ADD CONSTRAINT DF_Customer_Metrics DEFAULT 1 for Metrics
GO
COMMIT
