/*
	THIS IS NEEDED SINCE THE PASSWORD EXPIRATION LOGIC WAS NEVER FIRING
	W/O THIS ALL USERS PASSWORDS WOULD EXPIRE AFTER ROLLOUT
*/
ALTER TABLE UserPassword DISABLE TRIGGER Tr_UserPassword_Update_Delete

UPDATE dbo.UserPassword
SET CreatedDate = GETDATE()
FROM dbo.UserPassword
WHERE UserPasswordID IN (SELECT MAX(UserPasswordID) FROM dbo.UserPassword GROUP BY UserID)

ALTER TABLE UserPassword ENABLE TRIGGER Tr_UserPassword_Update_Delete