use role sysadmin;

create database if not exists "BILLING_DEV" ;

use role securityadmin;

--Grant ALL PRIVILEGES on database and all associated schemas to the "all" role
GRANT ALL ON DATABASE BILLING_DEV TO ROLE BILLING_ARCHIVE_all;
GRANT ALL ON ALL SCHEMAS IN DATABASE BILLING_DEV TO ROLE BILLING_ARCHIVE_all;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE BILLING_DEV TO ROLE BILLING_ARCHIVE_all;
GRANT ALL ON ALL TABLES IN DATABASE BILLING_DEV TO ROLE BILLING_ARCHIVE_all;
GRANT ALL ON FUTURE TABLES IN DATABASE BILLING_DEV TO ROLE BILLING_ARCHIVE_all;

--Grant USAGE (connect) on database and all associated schemas to the "read" role
GRANT USAGE ON ALL SCHEMAS IN DATABASE BILLING_DEV TO ROLE BILLING_ARCHIVE_read;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE BILLING_DEV TO ROLE BILLING_ARCHIVE_read;
GRANT USAGE ON DATABASE BILLING_DEV TO ROLE BILLING_ARCHIVE_read;

--Grant Table privileges
GRANT SELECT ON ALL TABLES IN DATABASE BILLING_DEV TO ROLE BILLING_ARCHIVE_read;
GRANT SELECT ON FUTURE TABLES IN DATABASE BILLING_DEV TO ROLE BILLING_ARCHIVE_read;
GRANT INSERT,UPDATE,DELETE,TRUNCATE ON ALL TABLES IN DATABASE BILLING_DEV TO ROLE BILLING_ARCHIVE_write;
GRANT INSERT,UPDATE,DELETE,TRUNCATE ON FUTURE TABLES IN DATABASE BILLING_DEV TO ROLE BILLING_ARCHIVE_write;
