Use ReportingLog;

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'HDP_CustomerMapping')
  DROP TABLE dbo.HDP_CustomerMapping;


IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'HDP_CustomerMappingException')
  DROP TABLE dbo.HDP_CustomerMappingException;


IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'HDP_Source')
  DROP TABLE dbo.HDP_Source;


IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'HDP_ImportType')
  DROP TABLE dbo.HDP_ImportType;


IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'HDP_DataImportJobs')
  DROP TABLE dbo.HDP_DataImportJobs;


IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'HDP_DataImportLogs')
  DROP TABLE dbo.HDP_DataImportLogs;


IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'HDP_DataEtlJobs')
  DROP TABLE dbo.HDP_DataEtlJobs;


IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'HDP_DataEtlScriptLogs')
  DROP TABLE dbo.HDP_DataEtlScriptLogs;


IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'HDP_DataEtlScriptStatementLogs')
  DROP TABLE dbo.HDP_DataEtlScriptStatementLogs;

