DECLARE @StartDt DATETIME
DECLARE @EndDt DATETIME
SET @StartDt='1-1-2000'
SET @EndDt='12-31-2100'

DECLARE @Loop INT
DECLARE @Count INT
DECLARE @WKCount INT

DECLARE @CMo INT
DECLARE @MC INT
DECLARE @TC INT
DECLARE @WC INT
DECLARE @THC INT
DECLARE @FC INT
DECLARE @SC INT
DECLARE @SNC INT
DECLARE @WDIM INT

SET @CMo=0
SET @MC=0
SET @TC=0
SET @WC=0
SET @THC=0
SET @FC=0
SET @SC=0
SET @SNC=0

SET @Count=0
SET @Loop=DATEDIFF(D,@StartDt,@EndDt)
SET @WKCount=1

DECLARE @CurrentDt DATETIME

IF EXISTS(SELECT * FROM sysobjects WHERE xtype='U' AND name='DateKey')
	DROP TABLE DateKey

--Dt=Date, D=Day, WD=WeekDay, WDIM=WeekDay In Month, WK=WeekID, Mo=Month, MoID= Month Count From @StartDt, Yr=Year
CREATE TABLE DateKey(DKID INT IDENTITY(1,1), Dt DATETIME, D INT, LastDay BIT, WD INT, WDIM INT, LastWD BIT, LastWEDay BIT, LastWKDay BIT, Wk INT, Mo INT, MoID INT, MoDays INT, Yr INT)

SET @CurrentDt=@StartDt

IF @CMo<>DATEPART(M,@CurrentDt)
BEGIN
	SET @CMo=DATEPART(M,@CurrentDt)
	SET @MC=0
	SET @TC=0
	SET @WC=0
	SET @THC=0
	SET @FC=0
	SET @SC=0
	SET @SNC=0
END

IF DATEPART(DW,@CurrentDt)=1
BEGIN
	SET @SNC=@SNC+1
	SET @WDIM=@SNC
END
IF DATEPART(DW,@CurrentDt)=2
BEGIN
	SET @MC=@MC+1
	SET @WDIM=@MC
END
IF DATEPART(DW,@CurrentDt)=3
BEGIN
	SET @TC=@TC+1
	SET @WDIM=@TC
END
IF DATEPART(DW,@CurrentDt)=4
BEGIN
	SET @WC=@WC+1
	SET @WDIM=@WC
END
IF DATEPART(DW,@CurrentDt)=5
BEGIN
	SET @THC=@THC+1
	SET @WDIM=@THC
END
IF DATEPART(DW,@CurrentDt)=6
BEGIN
	SET @FC=@FC+1	
	SET @WDIM=@FC
END
IF DATEPART(DW,@CurrentDt)=7
BEGIN
	SET @SC=@SC+1
	SET @WDIM=@SC
END

INSERT INTO DateKey(Dt, D, WD, WDIM, Wk, Mo, Yr)
VALUES(@CurrentDt, DATEPART(D,@CurrentDt), DATEPART(DW, @CurrentDt), @WDIM, @WKCount, DATEPART(M,@CurrentDt), DATEPART(YYYY,@CurrentDt))

WHILE @Count<@Loop
BEGIN

	SET @Count=@Count+1
	
	SET @CurrentDt=@StartDt+@Count

	IF @CMo<>DATEPART(M,@CurrentDt)
	BEGIN
		SET @CMo=DATEPART(M,@CurrentDt)
		SET @MC=0
		SET @TC=0
		SET @WC=0
		SET @THC=0
		SET @FC=0
		SET @SC=0
		SET @SNC=0
	END
	
	IF DATEPART(DW,@CurrentDt)=1
	BEGIN
		SET @SNC=@SNC+1
		SET @WDIM=@SNC
	END
	IF DATEPART(DW,@CurrentDt)=2
	BEGIN
		SET @MC=@MC+1
		SET @WDIM=@MC
	END
	IF DATEPART(DW,@CurrentDt)=3
	BEGIN
		SET @TC=@TC+1
		SET @WDIM=@TC
	END
	IF DATEPART(DW,@CurrentDt)=4
	BEGIN
		SET @WC=@WC+1
		SET @WDIM=@WC
	END
	IF DATEPART(DW,@CurrentDt)=5
	BEGIN
		SET @THC=@THC+1
		SET @WDIM=@THC
	END
	IF DATEPART(DW,@CurrentDt)=6
	BEGIN
		SET @FC=@FC+1	
		SET @WDIM=@FC
	END
	IF DATEPART(DW,@CurrentDt)=7
	BEGIN
		SET @SC=@SC+1
		SET @WDIM=@SC
	END

	INSERT INTO DateKey(Dt, D, WD, WDIM, Wk, Mo, Yr)
	VALUES(@CurrentDt, DATEPART(D,@CurrentDt), DATEPART(DW, @CurrentDt), @WDIM, @WKCount, DATEPART(M,@CurrentDt), DATEPART(YYYY,@CurrentDt))

	IF DATEPART(DW,@CurrentDt)%7=0
		SET @WKCount=@WKCount+1
END

DECLARE @Last TABLE(WD INT, Mo INT, Yr INT, MAXWDIM INT)
INSERT @Last(WD, Mo, Yr, MAXWDIM)
SELECT WD, Mo, Yr, MAX(WDIM)
FROM DateKey
GROUP BY WD, Mo, Yr

UPDATE DK SET LastWD=1
FROM DateKey DK INNER JOIN @Last L
ON DK.WD=L.WD AND DK.Mo=L.Mo AND DK.Yr=L.Yr AND DK.WDIM=L.MAXWDIM

UPDATE DateKey SET LastWD=0
WHERE LastWD IS NULL

CREATE TABLE #Mos(MID INT IDENTITY(1,1), Mo INT, Yr INT, LastDay INT, LastWEDay INT, LastWKDay INT)
INSERT INTO #Mos(Mo, Yr, LastDay, LastWEDay, LastWKDay)
SELECT DISTINCT Mo, Yr, MAX(D) LastDay, MAX(CASE WHEN WD IN (1,7) THEN D END) LastWEDay, MAX(CASE WHEN WD IN (2,3,4,5,6) THEN D END) LastWKDay
FROM DateKey
GROUP BY Mo, Yr
ORDER BY YR, Mo

UPDATE DK SET MoID=MID, MoDays=M.LastDay
FROM DateKey DK INNER JOIN #Mos M
ON DK.Yr=M.Yr AND DK.Mo=M.Mo

UPDATE DK SET LastDay=1
FROM DateKey DK INNER JOIN #Mos M
ON DK.Yr=M.Yr AND DK.Mo=M.Mo AND DK.D=M.LastDay

UPDATE DK SET LastWEDay=1
FROM DateKey DK INNER JOIN #Mos M
ON DK.Yr=M.Yr AND DK.Mo=M.Mo AND DK.D=M.LastWEDay

UPDATE DK SET LastWKDay=1
FROM DateKey DK INNER JOIN #Mos M
ON DK.Yr=M.Yr AND DK.Mo=M.Mo AND DK.D=M.LastWKDay

UPDATE DateKey SET LastDay=0
WHERE LastDay IS NULL

UPDATE DateKey SET LastWEDay=0
WHERE LastWEDay IS NULL

UPDATE DateKey SET LastWKDay=0
WHERE LastWKDay IS NULL

CREATE UNIQUE CLUSTERED INDEX CI_DateKey_Dt
ON DateKey (Dt, D, LastDay, WD, WDIM, LastWD, LastWEDay, LastWKDay, Mo, MoDays, Yr)

DROP TABLE #Mos

SELECT *
FROM DateKey
ORDER BY Dt DESC