-- TAKE A BACKUP OF EDIHACKPAYER FIRST

DECLARE @THRESHOLD INT = 3

SELECT
	MIN(CustomerId) as CUSTOMERID,
	MIN(PracticeId) as PRACTICEID,
	PAYERNUMBER,
	EDIHACKID,
	EDIBILLXMLV1,
	EDIBILLXMLV2,
	EDIBILLXMLV2I,
	EDIBILLXML5010,
	EDIBILLXML5010I,
	REFERENCEVALUE1,
	REFERENCEVALUE1TYPEID,
	CUSTOMVALUE,
	REFERENCEVALUE2,
	REFERENCEVALUE2TYPEID,
	COUNT(*) as [COUNT]
INTO 
	#EDIHACKPAYERTEMP
FROM
	EdiHackPayer
GROUP BY
	PAYERNUMBER,
	EdiHackID,
	EDIBILLXMLV1,
	EDIBILLXMLV2,
	EDIBILLXMLV2I,
	EDIBILLXML5010,
	EDIBILLXML5010I,
	REFERENCEVALUE1,
	REFERENCEVALUE1TYPEID,
	CUSTOMVALUE,
	REFERENCEVALUE2,
	REFERENCEVALUE2TYPEID
ORDER BY
	PAYERNUMBER,
	EDIHACKID
	
SELECT
	*
INTO
	#EDIHACKPAYERFINAL
FROM
	EDIHACKPAYER


TRUNCATE TABLE EDIHACKPAYER

-- UNIQUE HAX

INSERT INTO
	EDIHACKPAYER
(
	CUSTOMERID, 
	PRACTICEID, 
	PAYERNUMBER, 
	EDIHACKID, 
	EDIBILLXMLV1, 
	EDIBILLXMLV2, 
	EDIBILLXMLV2I, 
	EDIBILLXML5010, 
	EDIBILLXML5010I,
	REFERENCEVALUE1,
	REFERENCEVALUE1TYPEID,
	CUSTOMVALUE,
	REFERENCEVALUE2,
	REFERENCEVALUE2TYPEID
)
SELECT
	CUSTOMERID, 
	PRACTICEID, 
	PAYERNUMBER, 
	EDIHACKID, 
	EDIBILLXMLV1, 
	EDIBILLXMLV2, 
	EDIBILLXMLV2I, 
	EDIBILLXML5010, 
	EDIBILLXML5010I,
	REFERENCEVALUE1,
	REFERENCEVALUE1TYPEID,
	CUSTOMVALUE,
	REFERENCEVALUE2,
	REFERENCEVALUE2TYPEID
FROM
	#EDIHACKPAYERTEMP
WHERE [COUNT] <= @THRESHOLD

-- GLOBAL PAYER HAX

INSERT INTO
	EDIHACKPAYER
(
	PAYERNUMBER, 
	EDIHACKID, 
	EDIBILLXMLV1, 
	EDIBILLXMLV2, 
	EDIBILLXMLV2I, 
	EDIBILLXML5010, 
	EDIBILLXML5010I,
	REFERENCEVALUE1,
	REFERENCEVALUE1TYPEID,
	CUSTOMVALUE,
	REFERENCEVALUE2,
	REFERENCEVALUE2TYPEID
)
SELECT
	PAYERNUMBER, 
	EDIHACKID, 
	EDIBILLXMLV1, 
	EDIBILLXMLV2, 
	EDIBILLXMLV2I, 
	EDIBILLXML5010, 
	EDIBILLXML5010I,
	REFERENCEVALUE1,
	REFERENCEVALUE1TYPEID,
	CUSTOMVALUE,
	REFERENCEVALUE2,
	REFERENCEVALUE2TYPEID
FROM
	#EDIHACKPAYERTEMP
WHERE [COUNT] > @THRESHOLD

DROP TABLE #EDIHACKPAYERTEMP