SET ANSI_NULLS OFF

-- CREATE TEMP VARIABLES
DECLARE
	@NAME NVARCHAR(100), @EDIHACKID INT, @PAYERNUMBER NVARCHAR(64),
	@EDIBILLXMLV1 BIT, @EDIBILLXMLV2 BIT, @EDIBILLXMLV2I BIT,
	@EDIBILLXML5010 BIT, @EDIBILLXML5010I BIT, @REFERENCEVALUE1 NVARCHAR(100),
	@REFERENCEVALUE1TYPEID INT, @CUSTOMVALUE NVARCHAR(100), @REFERENCEVALUE2 VARCHAR(100), @REFERENCEVALUE2TYPEID INT
	
-- ---
-- SET UP WHAT HACK SHOULD BECOME GLOBAL
SELECT
	@NAME = 'ClaimControlInREFF8',
	@PAYERNUMBER = 'BS022',
	@EDIBILLXMLV1 = 0,
	@EDIBILLXMLV2 = 0,
	@EDIBILLXMLV2I = 0,
	@EDIBILLXML5010 = 1,
	@EDIBILLXML5010I = 0,
	@REFERENCEVALUE1 = null,
	@REFERENCEVALUE1TYPEID = null,
	@CUSTOMVALUE = null,
	@REFERENCEVALUE2 = null,
	@REFERENCEVALUE2TYPEID = null
	
-- SELECT THE HACK ID TO USE
SELECT
	@EDIHACKID = ( SELECT TOP 1 EDIHACKID FROM EdiHack WHERE Name = @NAME )

-- DELETE ALL SPECIFIC HACK OCCURENCES
DELETE FROM
	EdiHackPayer
WHERE
	EdiHackID = @EDIHACKID
	AND
	PayerNumber = @PAYERNUMBER
	AND
	EDIBILLXMLV1 = @EDIBILLXMLV1
	AND
	EDIBILLXMLV2 = @EDIBILLXMLV2
	AND
	EDIBILLXMLV2I = @EDIBILLXMLV2I
	AND
	EDIBILLXML5010 = @EDIBILLXML5010
	AND
 	EDIBILLXML5010I = @EDIBILLXML5010I
	AND
	REFERENCEVALUE1 = @REFERENCEVALUE1
	AND
	REFERENCEVALUE1TYPEID = @REFERENCEVALUE1TYPEID
	AND
	CUSTOMVALUE = @CUSTOMVALUE
	AND
	REFERENCEVALUE2 = @REFERENCEVALUE2
	AND
	REFERENCEVALUE2TYPEID = @REFERENCEVALUE2TYPEID
	
-- REINSERT THE HACK AS A GLOBAL HACK
INSERT INTO EdiHackPayer
(
	EDIHACKID,
	PAYERNUMBER,
	EDIBILLXMLV1,
	EDIBILLXMLV2,
	EDIBILLXMLV2I,
	EDIBILLXML5010,
	EDIBILLXML5010I,
	REFERENCEVALUE1,
	REFERENCEVALUE1TYPEID,
	CUSTOMVALUE,
	REFERENCEVALUE2,
	REFERENCEVALUE2TYPEID
)
VALUES
(
	@EDIHACKID,
	@PAYERNUMBER,
	@EDIBILLXMLV1,
	@EDIBILLXMLV2,
	@EDIBILLXMLV2I,
	@EDIBILLXML5010,
	@EDIBILLXML5010I,
	@REFERENCEVALUE1,
	@REFERENCEVALUE1TYPEID,
	@CUSTOMVALUE,
	@REFERENCEVALUE2,
	@REFERENCEVALUE2TYPEID
)