DECLARE @T TABLE(TID INT IDENTITY(1,1), PlanName VARCHAR(50), ICPID INT)

INSERT @T (PlanName,ICPID)
VALUES('A',1)
INSERT @T (PlanName,ICPID)
VALUES('A',2)
INSERT @T (PlanName,ICPID)
VALUES('A',3)

INSERT @T (PlanName,ICPID)
VALUES('B',4)
INSERT @T (PlanName,ICPID)
VALUES('B',5)

SELECT *
FROM @T

DECLARE @TF TABLE(PlanName VARCHAR(50), ICPID INT)
INSERT @TF(PlanName, ICPID)
SELECT T.PlanName, T.ICPID
FROM @T T INNER JOIN (SELECT PlanName, MIN(TID) MIN_ID FROM @T GROUP BY PlanName) TF
ON T.TID=TF.MIN_ID

SELECT *
FROM @TF