name: hadoop-import
channels: !!python/tuple
- defaults
- conda-forge
dependencies:
- freetds=1.00.44
- impyla=0.14.0
- mock=2.0.0
- pyspark=2.3.0
- pymssql=2.1.3
- python=2.7.13
- sasl=0.2.1
- thrift=0.9.3
- pip:
  - teamcity-messages==1.21
  - thrift-sasl==0.2.1
