insert into adjustment( adjustmentCode, Description, systemCode )
select adjustmentCode, Description, systemCode 
from [KPROD-DB12].superbill_0644_prod.dbo.adjustment
where adjustmentCode not in (select adjustmentCode from adjustment )


INSERT INTO [dbo].[InsuranceCompany](
	[InsuranceCompanyName]
	,[Notes]
	,[AddressLine1]
	,[AddressLine2]
	,[City]
	,[State]
	,[Country]
	,[ZipCode]
	,[ContactPrefix]
	,[ContactFirstName]
	,[ContactMiddleName]
	,[ContactLastName]
	,[ContactSuffix]
	,[Phone]
	,[PhoneExt]
	,[Fax]
	,[FaxExt]
	,[BillSecondaryInsurance]
	,[EClaimsAccepts]
	,[BillingFormID]
	,[InsuranceProgramCode]
	,[HCFADiagnosisReferenceFormatCode]
	,[HCFASameAsInsuredFormatCode]
	,[LocalUseFieldTypeCode]
	,[ReviewCode]
	,[ProviderNumberTypeID]
	,[GroupNumberTypeID]
	,[LocalUseProviderNumberTypeID]
	,[CompanyTextID]
	,[ClearinghousePayerID]
	,[CreatedPracticeID]
	,[CreatedDate]
	,[CreatedUserID]
	,[ModifiedDate]
	,[ModifiedUserID]
	,[KareoInsuranceCompanyID]
	,[KareoLastModifiedDate]
	,[SecondaryPrecedenceBillingFormID]
	,[VendorID]
	,[VendorImportID]
	,[DefaultAdjustmentCode]
	,[ReferringProviderNumberTypeID]
	,[NDCFormat]
	,[UseFacilityID]
	,[AnesthesiaType]
	,[InstitutionalBillingFormID]
	)
select 
	[InsuranceCompanyName]
	,[Notes]
	,[AddressLine1]
	,[AddressLine2]
	,[City]
	,[State]
	,[Country]
	,[ZipCode]
	,[ContactPrefix]
	,[ContactFirstName]
	,[ContactMiddleName]
	,[ContactLastName]
	,[ContactSuffix]
	,[Phone]
	,[PhoneExt]
	,[Fax]
	,[FaxExt]
	,[BillSecondaryInsurance]
	,[EClaimsAccepts]
	,[BillingFormID]
	,[InsuranceProgramCode]
	,[HCFADiagnosisReferenceFormatCode]
	,[HCFASameAsInsuredFormatCode]
	,[LocalUseFieldTypeCode]
	,[ReviewCode]
	,[ProviderNumberTypeID]
	,[GroupNumberTypeID]
	,[LocalUseProviderNumberTypeID]
	,[CompanyTextID]
	,[ClearinghousePayerID]
	,1 as [CreatedPracticeID]
	,getdate() as [CreatedDate]
	,0 as [CreatedUserID]
	,getdate() as [ModifiedDate]
	,0 [ModifiedUserID]
	,[KareoInsuranceCompanyID]
	,[KareoLastModifiedDate]
	,[SecondaryPrecedenceBillingFormID]
	,insuranceCompanyID as [VendorID]
	,1 as [VendorImportID]
	,[DefaultAdjustmentCode]
	,[ReferringProviderNumberTypeID]
	,[NDCFormat]
	,[UseFacilityID]
	,[AnesthesiaType]
	,[InstitutionalBillingFormID]
from [KPROD-DB12].superbill_0644_prod.dbo.insuranceCompany






INSERT INTO [dbo].[InsuranceCompanyPlan]
	([PlanName]
	,[AddressLine1]
	,[AddressLine2]
	,[City]
	,[State]
	,[Country]
	,[ZipCode]
	,[ContactPrefix]
	,[ContactFirstName]
	,[ContactMiddleName]
	,[ContactLastName]
	,[ContactSuffix]
	,[Phone]
	,[PhoneExt]
	,[Notes]
	,[MM_CompanyID]
	,[CreatedDate]
	,[CreatedUserID]
	,[ModifiedDate]
	,[ModifiedUserID]
	,[ReviewCode]
	,[CreatedPracticeID]
	,[Fax]
	,[FaxExt]
	,[KareoInsuranceCompanyPlanID]
	,[KareoLastModifiedDate]
	,[InsuranceCompanyID]
	,[ADS_CompanyID]
	,[Copay]
	,[Deductible]
	,[VendorID]
	,[VendorImportID]
)



select 
[PlanName]
	,icp.[AddressLine1]
	,icp.[AddressLine2]
	,icp.[City]
	,icp.[State]
	,icp.[Country]
	,icp.[ZipCode]
	,icp.[ContactPrefix]
	,icp.[ContactFirstName]
	,icp.[ContactMiddleName]
	,icp.[ContactLastName]
	,icp.[ContactSuffix]
	,icp.[Phone]
	,icp.[PhoneExt]
	,icp.[Notes]
	,[MM_CompanyID]
	,getdate() as [CreatedDate]
	,0 as [CreatedUserID]
	,getdate() [ModifiedDate]
	,0 as [ModifiedUserID]
	,icp.[ReviewCode]
	,1 as [CreatedPracticeID]
	,icp.[Fax]
	,icp.[FaxExt]
	,icp.[KareoInsuranceCompanyPlanID]
	,icp.[KareoLastModifiedDate]
	,ic.[InsuranceCompanyID]
	,[ADS_CompanyID]
	,[Copay]
	,[Deductible]
	,icp.insuranceCompanyPlanId as [VendorID]
	,1 as [VendorImportID]
from [KPROD-DB12].superbill_0644_prod.dbo.insuranceCompanyPlan icp
	inner join insuranceCompany ic
		on ic.vendorId=icp.insuranceCompanyId



