IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HMC_MWCAS]') AND type in (N'U'))
  BEGIN
	--DELETE FROM [dbo].[HMC_MWCAS]
	DROP TABLE [dbo].[HMC_MWCAS]
  END
GO

CREATE TABLE [dbo].[HMC_mwcas](
	--[Item] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ChartNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CaseNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Description] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Guarantor] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Print Patient Statements] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MaritalStatus] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Student Status] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EmploymentStatus] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Employer] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Employee Location] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Employee Retirement Date] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WorkPhone] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WorkPhoneExtension] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Insured1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InsuredRelationship1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InsuranceCarrier1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Accept Assignment #1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PolicyNumber1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GroupNumber1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered A #1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered B #1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered C #1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered D #1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered E #1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered F #1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered G #1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered H #1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Policy is Capitated] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Policy1StartDate] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Policy1EndDate] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CopaymentAmount] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Insured2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InsuredRelationship2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InsuranceCarrier2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Accept Assignment #2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PolicyNumber2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GroupNumber2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered A #2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered B #2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered C #2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered D #2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered E #2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered F #2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered G #2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered H #2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Policy2StartDate] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Policy2EndDate] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Policy #2 Crossover Claim] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Insured3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InsuredRelationship3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InsuranceCarrier3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Accept Assignment #3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PolicyNumber3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GroupNumber3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered A #3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered B #3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered C #3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered D #3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered E #3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered F #3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered G #3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Percent Covered H #3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Policy3StartDate] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Policy3EndDate] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Facility] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RelatedToEmployment] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RelatedToAccident] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Nature of Accident] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Same or Similar Symptoms] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Emergency] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[EPSDT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Family Planning] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Outside Lab Work] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Lab Charges] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateOfInjuryIllness] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateFirstConsulted] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateUnableToWorkFrom] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateUnableToWorkTo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateTotDisabilityFrom] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateTotDisabilityTo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Date Part Disability From] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Date Part Disability To] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HospitalDateFrom] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HospitalDateTo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Prior Authorization No] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Death Indicator] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Illness Indicator] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AccidentState] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateSimilarSymptoms] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Medicaid Resubmission No] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Medicaid Original Ref No] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Local Use A] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Local Use B] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Champus Nonavailability] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Champus Branch of Service] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Champus Sponsor Grade] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Champus Sponsor Status] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Champus Special Program] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Champus Card Start Date] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Champus Termination Date] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Return to Work Indicator] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Workers Percent Disabled] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Diagnosis1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Diagnosis2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Diagnosis3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Diagnosis4] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Last Xray Date] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Level of Subluxation] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMCNotes] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Visit Series ID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Visit Series Counter] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Last Visit Date] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Authorized No of Visits] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Visit Authorization No] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Treatment Auth Through] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Attorney] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ReferringProvider] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Assigned Provider] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Referral Source] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BillingCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PriceCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Indicator 1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Date Created] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Cash Case] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Case Closed] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Other Arrangements] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Extra 1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Extra 2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Extra 3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Extra 4] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Primary Care Provider] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Date Last Seen PCP] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Annual Deductible] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[User Code] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Treatment Months Years] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[No Treatments-Month] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Nature of Condition] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Date of Manifestation] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Complication Ind] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Radiographs enclosed] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Prosthesis] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Date of Prior Placement] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Reason for replacement] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Orthodontics] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Date Treatment Start] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Date Appliances Placed] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Length of Treatment] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Medical Plan Coverage] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Eligibility Verified] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Eligibility Verified Date] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Eligibility ID Number] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Eligibility Verifier] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Policy Type] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[PC Claim Number 1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[PC Claim Number 2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[PC Claim Number 3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Referral Date] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Pregnancy Indicator] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Estimated Date of Birth] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Prescription Date] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Last worked Date] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Date assumed care] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Date relinquished care] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Service Authorization Exception Code] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Report type code] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Report transmission code] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Homebound indicator] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[IDE Number] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Supervising Provider] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Attachment Control Number] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Deductible Met] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Notes] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Date Modified] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) 

GO

/*
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HMC_MWCLA]') AND type in (N'U'))
  BEGIN
	--DELETE FROM [dbo].[HMC_MWCLA]
	DROP TABLE [dbo].[HMC_MWCLA]
  END
GO

CREATE TABLE [dbo].[HMC_mwcla](
	--[Item] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ChartNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CaseNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BillingCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Indicator1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BatchNumber1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BatchNumber2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BatchNumber3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMCReceiver1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMCReceiver2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMCReceiver3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InsuranceCarrier1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InsuranceCarrier2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InsuranceCarrier3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Provider] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PrimaryBillingMethod] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SecondaryBillingMethod] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TertiaryBillingMethod] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimStatus1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimStatus2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimStatus3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PrimaryBillingDate] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SecondaryBillingDate] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TertiaryBillingDate] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PrimarySubmissionCount] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SecondarySubmissionCnt] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TertiarySubmissionCount] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateCreated] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Comment] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InitialBillingDate1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InitialBillingDate2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InitialBillingDate3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UserCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DiagnosisCode1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DiagnosisCode2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DiagnosisCode3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DiagnosisCode4] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateModified] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) 

GO

*/

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HMC_MWINS]') AND type in (N'U'))
  BEGIN
	--DELETE FROM [dbo].[HMC_MWINS]
	DROP TABLE [dbo].[HMC_MWINS]
  END
GO

CREATE TABLE [dbo].[HMC_mwins](
	--[Item] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Code] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Name] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[City] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[State] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZipCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Phone] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Extension] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Fax] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Contact] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PracticeIDNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PlanName] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Type] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ProcedureCodeSet] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DiagnosisCodeSet] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SignatureOnFile] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DelaySecondaryBilling] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DefaultBillingMethod] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMCReceiver] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMCPayorNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMCSubID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMCExtra1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMCExtra2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ETSRecordCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DefaultPaymentCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DefaultWriteOffCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DefaultWithholdCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DefaultDeductibleCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Indicator] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PrintPINsOnInsForm] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UserCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateCreated] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PhysicianSignatureOnFile] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InsuredSignatureOnFile] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CarrierIDNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HealthPlanIdentifier] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateModified] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Inactive] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IOD] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMCMaxTransactions] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DefaultTakeBackCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) 

GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HMC_MWPAT]') AND type in (N'U'))
  BEGIN
	--DELETE FROM [dbo].[HMC_MWPAT]
	DROP TABLE [dbo].[HMC_MWPAT]
  END
GO

CREATE TABLE [dbo].[HMC_mwpat](
	--[Item] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ChartNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastName] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FirstName] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MiddleName] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[City] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[State] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZipCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Phone1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Phone2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Phone 3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Phone 4] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Phone 5] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SocialSecurityNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Signature on File] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PatientType] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Patient ID #2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Gender] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateOfBirth] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Assigned Provider] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Country] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateOfLastPayment] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastPaymentAmount] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PatientReferenceBalance] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Date Created] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Employment Status] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Employer] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Employee Location] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Employee Retirement Date] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WorkPhone] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WorkExtension] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[SOF Date] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BillingCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Patient Indicator] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[User Code] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Unique Health ID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMail] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Date Modified] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ContactPhone1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ContactPhone2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ContactName] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Weight] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Weight Units] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Flag] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Inactive] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) 

GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HMC_MWPHY]') AND type in (N'U'))
  BEGIN
	--DELETE FROM [dbo].[HMC_MWPHY]
	DROP TABLE [dbo].[HMC_MWPHY]
  END
GO

CREATE TABLE [dbo].[HMC_mwphy](
	--[Item] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Code] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastName] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FirstName] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MiddleInitial] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Credentials] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[City] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[State] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZipCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Phone] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Fax] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SSNOrFedTaxID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FederalTaxIDIndicator] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LicenseNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SignatureOnFile] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MedicarePIN] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MedicaidPIN] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ChampusPIN] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BlueCrossShieldPIN] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CommercialPIN] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GroupPIN] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HMOPIN] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PPOPIN] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MedicareGroupID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MedicaidGroupID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BCBSGroupID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OtherGroupID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMCID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MedicareParticpProvider] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPIN] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Extra1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TaxonomyCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Specialty] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SecurityLevel] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SBNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SBReportFile] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SOFDate] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UserCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[DateCreated] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TATNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLIANumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NationalProviderIdentifier] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEARegistration] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMail] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Office] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Cell] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[DateModified] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Inactive] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) 

GO

/*
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HMC_MWPRO]') AND type in (N'U'))
  BEGIN
	--DELETE FROM [dbo].[HMC_MWPRO]
	DROP TABLE [dbo].[HMC_MWPRO]
  END
GO

CREATE TABLE [dbo].[HMC_mwpro](
	--[Item] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Code1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Code2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Code3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Type] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Description] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TypeOfService] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DefaultPlaceService1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DefaultPlaceService2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DefaultPlaceService3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TimeToDoProcedure] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InsuranceCategory] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PatientOnlyResponsible] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DonotPrintOnInsurance] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OnlyPrintOnInsurance] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CostOfServiceProduct] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MedicareAllowedAmount] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountA] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountB] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountC] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountD] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountE] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountF] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountG] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountH] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountI] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountJ] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountK] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountL] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountM] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountN] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountO] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountP] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountQ] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountR] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountS] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountU] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountV] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountW] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountX] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountY] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountZ] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AccountCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Taxable] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Inactive] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdjustmentAmountNegativ] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DefaultModifiers] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PrePayment] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DefaultModifier1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DefaultModifier2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DefaultModifier3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DefaultModifier4] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UserCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateCreated] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Approved] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RecallCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ValidSurfaces] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RevenueCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TaxRate] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateModified] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PurchasedService] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DefaultUnits] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) 

GO

*/

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HMC_MWRPH]') AND type in (N'U'))
  BEGIN
	--DELETE FROM [dbo].[HMC_MWRPH]
	DROP TABLE [dbo].[HMC_MWRPH]
  END
GO

CREATE TABLE [dbo].[HMC_mwrph](
	--[Item] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Code] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastName] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FirstName] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MiddleInitial] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Credentials] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[City] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[State] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZipCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Phone] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Fax] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SSNOrFedTaxID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FederalTaxIDIndicator] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LicenseNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SignatureOnFile] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MedicarePIN] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MedicaidPIN] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ChampusPIN] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BlueCrossShieldPIN] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CommercialPIN] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GroupPIN] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HMOPIN] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PPOPIN] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MedicareGroupID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MedicaidGroupID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BCBSGroupID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OtherGroupID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMCID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MedicareParticpProvider] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPIN] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Extra1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TaxonomyCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Specialty] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SecurityLevel] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SBNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SBReportFile] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SOFDate] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UserCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[DateCreated] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TATNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLIANumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NationalProviderIdentifier] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEARegistration] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMail] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Office] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Cell] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Date Modified] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Inactive] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) 

GO

/*
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HMC_MWTRN]') AND type in (N'U'))
  BEGIN
	--DELETE FROM [dbo].[HMC_MWTRN]
	DROP TABLE [dbo].[HMC_MWTRN]
  END
GO

CREATE TABLE [dbo].[HMC_mwtrn](
	--[Item] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ChartNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CaseNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EntryNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateFrom] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateTo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DocumentNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Description] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AttendingProvider] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ProcedureCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TransactionType] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InsuranceCategory] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Modifier1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Modifier2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Modifier3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Modifier4] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PlaceOfService] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TypeOfService] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VisitNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VisitTotalInSeries] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VisitSeriesID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Units] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Minutes] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Amount] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PriceIndicator] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Diagnosis1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Diagnosis2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Diagnosis3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Diagnosis4] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimItemRejected] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AcceptAssignment1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AcceptAssignment2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AcceptAssignment3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateCreated] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateOfFirstStatement] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateOfSecondStatement] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateOfLastStatement] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BilledToInsured1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BilledToInsured2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BilledToInsured3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GuarantorPaid] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Insurance1Paid] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Insurance2Paid] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Insurance3Paid] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GuarantorAmountPaid] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Insurance1AmountPaid] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Insurance2AmountPaid] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Insurance3AmountPaid] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GuarantorResponsible] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Insurance1Responsible] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Insurance2Responsible] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Insurance3Responsible] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WhoPaid] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DocumentationType] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Documentation] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AttorneyPaid] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AttorneyAmountPaid] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AttorneyResponsible] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdjustmentAmount] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UserCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AllowedAmount] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DiagnosisCode1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DiagnosisCode2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DiagnosisCode3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DiagnosisCode4] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCEntryNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ToothNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ToothSurface] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MouthQuadrant] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DepositID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CheckNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UnappliedAmount] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateModified] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Facility] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ProcedureDescription] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Diagnosis1Description] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Diagnosis2Description] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Diagnosis3Description] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Diagnosis4Description] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[StatementNumber] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) 

GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HMC_mwadd]') AND type in (N'U'))
  BEGIN
	--DELETE FROM [dbo].[HMC_mwadd]
	DROP TABLE [dbo].[HMC_mwadd]
  END
GO


CREATE TABLE [dbo].[HMC_mwadd](
	--[Item] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Code] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Name] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[City] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[State] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZipCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Phone] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Extension] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Fax] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Contact] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Type] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	--[EMail] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Office] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	--[Cell] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL

) 

GO

*/