USE superbill_5958_dev
GO


Declare @InsuranceIds Table (id integer primary Key not null)
Insert @InsuranceIds(id) values(51)
Insert @InsuranceIds(id) values(326)
Insert @InsuranceIds(id) values(8)
Insert @InsuranceIds(id) values(20)
Insert @InsuranceIds(id) values(123)
Insert @InsuranceIds(id) values(61)


Declare @InsId Integer
While exists (Select * From @InsuranceIds)
	Begin
		Select @InsId = Min(id) from @InsuranceIds
		

			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (2,@InsId,1,1,1,'','','','',62,'363L00000X','','','',0,1,1,'363L00000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (5,@InsId,1,1,1,'','','','',62,'193200000X','','','',0,1,1,'193200000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (53,@InsId,1,1,1,'','','','',62,'193200000X','','','',0,1,1,'193200000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (3,@InsId,1,1,1,'','','','',62,'193200000X','','','',0,1,1,'193200000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (1,@InsId,1,1,1,'','','','',62,'193200000X','','','',0,1,1,'193200000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (4,@InsId,1,1,1,'','','','',62,'193200000X','','','',0,1,1,'193200000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (52,@InsId,1,1,1,'','','','',62,'363L00000X','','','',0,1,1,'363L00000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (6,@InsId,1,1,1,'','','','',62,'363L00000X','','','',0,1,1,'363L00000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (7,@InsId,1,1,1,'','','','',62,'193200000X','','','',0,1,1,'193200000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (8,@InsId,1,1,1,'','','','',62,'193200000X','','','',0,1,1,'193200000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (9,@InsId,1,1,1,'','','','',62,'193200000X','','','',0,1,1,'193200000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (15,@InsId,1,1,1,'','','','',62,'363L00000X','','','',0,1,1,'363L00000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (18,@InsId,1,1,1,'','','','',62,'363L00000X','','','',0,1,1,'363L00000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (30,@InsId,1,1,1,'','','','',62,'363L00000X','','','',0,1,1,'363L00000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (16,@InsId,1,1,1,'','','','',62,'193200000X','','','',0,1,1,'193200000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (10,@InsId,1,1,1,'','','','',62,'193200000X','','','',0,1,1,'193200000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (21,@InsId,1,1,1,'','','','',62,'363L00000X','','','',0,1,1,'363L00000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (27,@InsId,1,1,1,'','','','',62,'363L00000X','','','',0,1,1,'363L00000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (14,@InsId,1,1,1,'','','','',62,'363L00000X','','','',0,1,1,'363L00000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (13,@InsId,1,1,1,'','','','',62,'363L00000X','','','',0,1,1,'363L00000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (19,@InsId,1,1,1,'','','','',62,'193200000X','','','',0,1,1,'193200000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (20,@InsId,1,1,1,'','','','',62,'193200000X','','','',0,1,1,'193200000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (22,@InsId,1,1,1,'','','','',62,'367500000X','','','',0,1,1,'367500000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (49,@InsId,1,1,1,'','','','',62,'367500000X','','','',0,1,1,'367500000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (26,@InsId,1,1,1,'','','','',62,'367500000X','','','',0,1,1,'367500000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (44,@InsId,1,1,1,'','','','',62,'367500000X','','','',0,1,1,'367500000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (45,@InsId,1,1,1,'','','','',62,'367500000X','','','',0,1,1,'367500000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (46,@InsId,1,1,1,'','','','',62,'367500000X','','','',0,1,1,'367500000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (24,@InsId,1,1,1,'','','','',62,'367500000X','','','',0,1,1,'367500000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (47,@InsId,1,1,1,'','','','',62,'367500000X','','','',0,1,1,'367500000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (28,@InsId,1,1,1,'','','','',62,'193200000X','','','',0,1,1,'193200000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (50,@InsId,1,1,1,'','','','',62,'193200000X','','','',0,1,1,'193200000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (23,@InsId,1,1,1,'','','','',62,'193200000X','','','',0,1,1,'193200000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (29,@InsId,1,1,1,'','','','',62,'193200000X','','','',0,1,1,'193200000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (42,@InsId,1,1,1,'','','','',62,'193200000X','','','',0,1,1,'193200000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (43,@InsId,1,1,1,'','','','',62,'193200000X','','','',0,1,1,'193200000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (48,@InsId,1,1,1,'','','','',62,'193200000X','','','',0,1,1,'193200000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (51,@InsId,1,1,1,'','','','',62,'193200000X','','','',0,1,1,'193200000X',0,0,0)
			INSERT INTO [dbo].[ClaimSettings] ([DoctorID],[InsuranceCompanyID],[ClaimSettingsTaxIDTypeID],[ClaimSettingsNPITypeID],[ShowAdvancedSettings],[ProviderNumber1],[ProviderNumber2],[ProviderNumber3],[ProviderNumber4],[GroupNumberType1],[GroupNumber1],[GroupNumber2],[GroupNumber3],[GroupNumber4],[EligibilityOverride],[EligibilityNPITypeID],[EligibilityTaxIDTypeID],[TaxonomyCode],[OverridePracticeNameFlag],[OverridePracticeAddressFlag],[OverridePayToAddressFlag]) VALUES (25,@InsId,1,1,1,'','','','',62,'193200000X','','','',0,1,1,'193200000X',0,0,0)

		Delete @InsuranceIds Where id = @InsId
	End




