SELECT 
      43 AS [PracticeID]
      ,[Prefix]
      ,[FirstName]
      ,[MiddleName]
      ,[LastName]
      ,[Suffix]
      ,[SSN]
      ,[AddressLine1]
      ,[AddressLine2]
      ,[City]
      ,[State]
      ,[Country]
      ,[ZipCode]
      ,[HomePhone]
      ,[HomePhoneExt]
      ,[WorkPhone]
      ,[WorkPhoneExt]
      ,[PagerPhone]
      ,[PagerPhoneExt]
      ,[MobilePhone]
      ,[MobilePhoneExt]
      ,[DOB]
      ,[EmailAddress]
      ,[Notes]
      ,[ActiveDoctor]
      ,[CreatedDate]
      ,[CreatedUserID]
      ,[ModifiedDate]
      ,[ModifiedUserID]
      ,[UserID]
      ,[Degree]
      ,[DefaultEncounterTemplateID]
      ,[TaxonomyCode]
      ,[DepartmentID]
      ,CAST(DoctorID AS VARCHAR) AS [VendorID]
      ,0 AS [VendorImportID]
      ,[FaxNumber]
      ,[FaxNumberExt]
      ,[OrigReferringPhysicianID]
      ,[External]
      ,[NPI]
      ,[ProviderTypeID]
      ,[ProviderPerformanceReportActive]
      ,[ProviderPerformanceScope]
      ,[ProviderPerformanceFrequency]
      ,[ProviderPerformanceDelay]
      ,[ProviderPerformanceCarbonCopyEmailRecipients]
      ,[ExternalBillingID]
      ,[GlobalPayToAddressFlag]
      ,[GlobalPayToName]
      ,[GlobalPayToAddressLine1]
      ,[GlobalPayToAddressLine2]
      ,[GlobalPayToCity]
      ,[GlobalPayToState]
      ,[GlobalPayToZipCode]
      ,[GlobalPayToCountry]
  FROM [superbill_5075_prod].[dbo].[Doctor]
WHERE PracticeID = 4 AND [External] = 1
UNION ALL
SELECT 
      44 AS [PracticeID]
      ,[Prefix]
      ,[FirstName]
      ,[MiddleName]
      ,[LastName]
      ,[Suffix]
      ,[SSN]
      ,[AddressLine1]
      ,[AddressLine2]
      ,[City]
      ,[State]
      ,[Country]
      ,[ZipCode]
      ,[HomePhone]
      ,[HomePhoneExt]
      ,[WorkPhone]
      ,[WorkPhoneExt]
      ,[PagerPhone]
      ,[PagerPhoneExt]
      ,[MobilePhone]
      ,[MobilePhoneExt]
      ,[DOB]
      ,[EmailAddress]
      ,[Notes]
      ,[ActiveDoctor]
      ,[CreatedDate]
      ,[CreatedUserID]
      ,[ModifiedDate]
      ,[ModifiedUserID]
      ,[UserID]
      ,[Degree]
      ,[DefaultEncounterTemplateID]
      ,[TaxonomyCode]
      ,[DepartmentID]
      ,CAST(DoctorID AS VARCHAR) AS [VendorID]
      ,0 AS [VendorImportID]
      ,[FaxNumber]
      ,[FaxNumberExt]
      ,[OrigReferringPhysicianID]
      ,[External]
      ,[NPI]
      ,[ProviderTypeID]
      ,[ProviderPerformanceReportActive]
      ,[ProviderPerformanceScope]
      ,[ProviderPerformanceFrequency]
      ,[ProviderPerformanceDelay]
      ,[ProviderPerformanceCarbonCopyEmailRecipients]
      ,[ExternalBillingID]
      ,[GlobalPayToAddressFlag]
      ,[GlobalPayToName]
      ,[GlobalPayToAddressLine1]
      ,[GlobalPayToAddressLine2]
      ,[GlobalPayToCity]
      ,[GlobalPayToState]
      ,[GlobalPayToZipCode]
      ,[GlobalPayToCountry]
  FROM [superbill_5075_prod].[dbo].[Doctor]
WHERE PracticeID = 4 AND [External] = 1




