
INSERT INTO [Adjustment]
           ([AdjustmentCode]
           ,[Description]
           ,[DefaultAdjustmentReasonCode]
           ,[SystemCode])
select 
a.[AdjustmentCode]
           ,a.[Description]
           ,a.[DefaultAdjustmentReasonCode]
           ,a.[SystemCode]
from [kprod-db09].superbill_0644_prod.[dbo].adjustment a
	left join adjustment aa
	on aa.adjustmentCode=a.adjustmentCode
where aa.adjustmentCode is null


INSERT INTO [dbo].[InsuranceCompany]
           ([InsuranceCompanyName]
           ,[Notes]
           ,[AddressLine1]
           ,[AddressLine2]
           ,[City]
           ,[State]
           ,[Country]
           ,[ZipCode]
           ,[ContactPrefix]
           ,[ContactFirstName]
           ,[ContactMiddleName]
           ,[ContactLastName]
           ,[ContactSuffix]
           ,[Phone]
           ,[PhoneExt]
           ,[Fax]
           ,[FaxExt]
           ,[BillSecondaryInsurance]
           ,[EClaimsAccepts]
           ,[BillingFormID]
           ,[InsuranceProgramCode]
           ,[HCFADiagnosisReferenceFormatCode]
           ,[HCFASameAsInsuredFormatCode]
           ,[LocalUseFieldTypeCode]
           ,[ReviewCode]
           ,[ProviderNumberTypeID]
           ,[GroupNumberTypeID]
           ,[LocalUseProviderNumberTypeID]
           ,[CompanyTextID]
           ,[ClearinghousePayerID]
           ,[CreatedPracticeID]
           ,[CreatedDate]
           ,[CreatedUserID]
           ,[ModifiedDate]
           ,[ModifiedUserID]
           ,[KareoInsuranceCompanyID]
           ,[KareoLastModifiedDate]
           ,[SecondaryPrecedenceBillingFormID]
           ,[VendorID]
           ,[VendorImportID]
           ,[DefaultAdjustmentCode]
           ,[ReferringProviderNumberTypeID]
           ,[NDCFormat]
           ,[UseFacilityID]
           ,[AnesthesiaType])
select
[InsuranceCompanyName]
           ,[Notes]
           ,[AddressLine1]
           ,[AddressLine2]
           ,[City]
           ,[State]
           ,[Country]
           ,[ZipCode]
           ,[ContactPrefix]
           ,[ContactFirstName]
           ,[ContactMiddleName]
           ,[ContactLastName]
           ,[ContactSuffix]
           ,[Phone]
           ,[PhoneExt]
           ,[Fax]
           ,[FaxExt]
           ,[BillSecondaryInsurance]
           ,[EClaimsAccepts]
           ,[BillingFormID]
           ,[InsuranceProgramCode]
           ,[HCFADiagnosisReferenceFormatCode]
           ,[HCFASameAsInsuredFormatCode]
           ,[LocalUseFieldTypeCode]
           ,[ReviewCode]
           ,[ProviderNumberTypeID]
           ,[GroupNumberTypeID]
           ,[LocalUseProviderNumberTypeID]
           ,[CompanyTextID]
           ,[ClearinghousePayerID]
           ,[CreatedPracticeID]
           ,[CreatedDate]
           ,[CreatedUserID]
           ,[ModifiedDate]
           ,[ModifiedUserID]
           ,[KareoInsuranceCompanyID]
           ,[KareoLastModifiedDate]
           ,[SecondaryPrecedenceBillingFormID]
           ,insuranceCompanyID
           ,[VendorImportID]
           ,[DefaultAdjustmentCode]
           ,[ReferringProviderNumberTypeID]
           ,[NDCFormat]
           ,[UseFacilityID]
           ,[AnesthesiaType]
FROM [kprod-db09].superbill_0644_prod.[dbo].[InsuranceCompany]



INSERT INTO [dbo].[InsuranceCompanyPlan]
           ([PlanName]
           ,[AddressLine1]
           ,[AddressLine2]
           ,[City]
           ,[State]
           ,[Country]
           ,[ZipCode]
           ,[ContactPrefix]
           ,[ContactFirstName]
           ,[ContactMiddleName]
           ,[ContactLastName]
           ,[ContactSuffix]
           ,[Phone]
           ,[PhoneExt]
           ,[Notes]
           ,[MM_CompanyID]
           ,[CreatedDate]
           ,[CreatedUserID]
           ,[ModifiedDate]
           ,[ModifiedUserID]
           ,[ReviewCode]
           ,[CreatedPracticeID]
           ,[Fax]
           ,[FaxExt]
           ,[KareoInsuranceCompanyPlanID]
           ,[KareoLastModifiedDate]
           ,[InsuranceCompanyID]
           ,[ADS_CompanyID]
           ,[Copay]
           ,[Deductible]
           ,[VendorID]
           ,[VendorImportID])
select ip.[PlanName]
           ,ip.[AddressLine1]
           ,ip.[AddressLine2]
           ,ip.[City]
           ,ip.[State]
           ,ip.[Country]
           ,ip.[ZipCode]
           ,ip.[ContactPrefix]
           ,ip.[ContactFirstName]
           ,ip.[ContactMiddleName]
           ,ip.[ContactLastName]
           ,ip.[ContactSuffix]
           ,ip.[Phone]
           ,ip.[PhoneExt]
           ,ip.[Notes]
           ,ip.[MM_CompanyID]
           ,ip.[CreatedDate]
           ,ip.[CreatedUserID]
           ,ip.[ModifiedDate]
           ,ip.[ModifiedUserID]
           ,ip.[ReviewCode]
           ,1
           ,ip.[Fax]
           ,ip.[FaxExt]
           ,ip.[KareoInsuranceCompanyPlanID]
           ,ip.[KareoLastModifiedDate]
           ,ic.[InsuranceCompanyID] as [InsuranceCompanyID]
           ,ip.[ADS_CompanyID]
           ,ip.[Copay]
           ,ip.[Deductible]
           ,ip.InsuranceCompanyPlanID [VendorID]
           ,ip.[VendorImportID]
from [kprod-db09].superbill_0644_prod.[dbo].[InsuranceCompanyPlan] ip
	left join [dbo].[InsuranceCompany] ic on ic.vendorID=ip.[InsuranceCompanyID]

select * from  [kprod-db09].superbill_0644_prod.[dbo].doctor



INSERT INTO [dbo].[Doctor]
           ([PracticeID]
           ,[Prefix]
           ,[FirstName]
           ,[MiddleName]
           ,[LastName]
           ,[Suffix]
           ,[SSN]
           ,[AddressLine1]
           ,[AddressLine2]
           ,[City]
           ,[State]
           ,[Country]
           ,[ZipCode]
           ,[HomePhone]
           ,[HomePhoneExt]
           ,[WorkPhone]
           ,[WorkPhoneExt]
           ,[PagerPhone]
           ,[PagerPhoneExt]
           ,[MobilePhone]
           ,[MobilePhoneExt]
           ,[DOB]
           ,[EmailAddress]
           ,[Notes]
           ,[ActiveDoctor]
           ,[CreatedDate]
           ,[CreatedUserID]
           ,[ModifiedDate]
           ,[ModifiedUserID]
           ,[UserID]
           ,[Degree]
           ,[DefaultEncounterTemplateID]
           ,[TaxonomyCode]
           ,[DepartmentID]
           ,[VendorID]
           ,[VendorImportID]
           ,[FaxNumber]
           ,[FaxNumberExt]
           ,[OrigReferringPhysicianID]
           ,[External]
           ,[NPI]
           ,[ProviderTypeID]
           ,[ProviderPerformanceReportActive]
           ,[ProviderPerformanceScope]
           ,[ProviderPerformanceFrequency]
           ,[ProviderPerformanceDelay]
           ,[ProviderPerformanceCarbonCopyEmailRecipients])
SELECT
1 as [PracticeID]
           ,[Prefix]
           ,[FirstName]
           ,[MiddleName]
           ,[LastName]
           ,[Suffix]
           ,[SSN]
           ,[AddressLine1]
           ,[AddressLine2]
           ,[City]
           ,[State]
           ,[Country]
           ,[ZipCode]
           ,[HomePhone]
           ,[HomePhoneExt]
           ,[WorkPhone]
           ,[WorkPhoneExt]
           ,[PagerPhone]
           ,[PagerPhoneExt]
           ,[MobilePhone]
           ,[MobilePhoneExt]
           ,[DOB]
           ,[EmailAddress]
           ,[Notes]
           ,[ActiveDoctor]
           ,[CreatedDate]
           ,[CreatedUserID]
           ,[ModifiedDate]
           ,[ModifiedUserID]
           ,[UserID]
           ,[Degree]
           ,[DefaultEncounterTemplateID]
           ,[TaxonomyCode]
           ,[DepartmentID]
           ,doctorID
           ,[VendorImportID]
           ,[FaxNumber]
           ,[FaxNumberExt]
           ,[OrigReferringPhysicianID]
           ,[External]
           ,[NPI]
           ,[ProviderTypeID]
           ,[ProviderPerformanceReportActive]
           ,[ProviderPerformanceScope]
           ,[ProviderPerformanceFrequency]
           ,[ProviderPerformanceDelay]
           ,[ProviderPerformanceCarbonCopyEmailRecipients]
From [kprod-db09].superbill_0644_prod.[dbo].doctor
where [External]=1
and practiceid=35

INSERT INTO [dbo].[ProviderNumber]
           ([DoctorID]
           ,[ProviderNumberTypeID]
           ,[InsuranceCompanyPlanID]
           ,[LocationID]
           ,[ProviderNumber]
           ,[AttachConditionsTypeID]
           ,[InsuranceCompanyID]
           ,[BillingNumberInsuranceScopeID])
select dd.[DoctorID]
           ,pn.[ProviderNumberTypeID]
           ,icp.[InsuranceCompanyPlanID]
           ,pn.[LocationID]
           ,pn.[ProviderNumber]
           ,pn.[AttachConditionsTypeID]
           ,ic.[InsuranceCompanyID]
           ,pn.[BillingNumberInsuranceScopeID]
from [kprod-db09].superbill_0644_prod.[dbo].ProviderNumber pn
inner join [kprod-db09].superbill_0644_prod.[dbo].doctor d on d.doctorID=pn.doctorID
left join insuranceCompany ic on ic.vendorID=pn.insuranceCompanyID
left join insuranceCompanyPlan icp on icp.vendorID=pn.insuranceCompanyPlanID
inner join doctor dd on dd.vendorID=d.doctorID
where d.[External]=1
and d.practiceid=35



INSERT INTO [dbo].[UserPractices]
           ([UserID]
           ,[PracticeID]
           ,[CreatedDate]
           ,[CreatedUserID]
           ,[ModifiedDate]
           ,[ModifiedUserID])
select [UserID]
           ,1
           ,[CreatedDate]
           ,[CreatedUserID]
           ,[ModifiedDate]
           ,[ModifiedUserID] from superbill_shared.dbo.users
where emailaddress in (
'tracy@med-billnc.com'
,'kworrell@med-billnc.com'
,'jennifer@med-billnc.com'
,'harry@med-billnc.com'
,'rob@med-billnc.com'
,'priscilla@med-billnc.com'
,'marilyn@med-billnc.com'
,'lynda@med-billnc.com'
,'dipal@med-billnc.com'
,'linda@med-billnc.com'
,'lisar@med-billnc.com'
,'Rose@med-billnc.com'
,'susie@med-billnc.com'
)
and userID not in (select userID from dbo.UserPractices)
