BEGIN TRANSACTION
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.Columns WHERE column_name='PMSEnabled' AND COLUMNS.TABLE_NAME='Customer')
ALTER TABLE dbo.Customer ADD
	PMSEnabled bit NOT NULL CONSTRAINT DF_Customer_PMSEnabled DEFAULT 1
GO
COMMIT