/**************************************/
/*Create Table UserAccount_Permissions*/
/**************************************/

USE [Superbill_Shared]
GO

/****** Object:  Table [dbo].[UserAccount_Permissions]    Script Date: 06/28/2012 14:49:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[UserAccount_Permissions](
	[PermissionID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Description] [varchar](1024) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[PermissionValue] [varchar](100) NOT NULL,
	[ViewInKareo] [bit] NOT NULL,
	[PermissionType] [int] NOT NULL,
	[HierarchyInfo] [varchar](100) NOT NULL,
	[Deleted] [bit] NOT NULL,
	[DateDeleted] [datetime] NULL,
	[QuestUserDenied] [bit] NOT NULL
 CONSTRAINT [PK_UserAccount_Permissions_PermissionID] PRIMARY KEY CLUSTERED 
(
	[PermissionID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[UserAccount_Permissions]  WITH CHECK ADD  CONSTRAINT [FK_UserAccount_Permissions_UserAccount_PermissionType] FOREIGN KEY([PermissionType])
REFERENCES [dbo].[UserAccount_PermissionType] ([Id])
GO

ALTER TABLE [dbo].[UserAccount_Permissions] CHECK CONSTRAINT [FK_UserAccount_Permissions_UserAccount_PermissionType]
GO

INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('A/R Aging By Insurance','',CURRENT_TIMESTAMP,'view_ARAgingByInsurance',1,2,'Reports>Accounts Recievable',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('A/R Aging By Patient','',CURRENT_TIMESTAMP,'view_ARAgingByPatient',1,2,'Reports>Accounts Recievable',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('A/R Aging Detail','',CURRENT_TIMESTAMP,'view_ARAgingDetail',1,2,'Reports>Accounts Recievable',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('A/R Aging Summary','',CURRENT_TIMESTAMP,'view_ARAgingSummary',1,2,'Reports>Accounts Recievable',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Access All Practices','',CURRENT_TIMESTAMP,'edit_AccessAllPractices',0,4,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Account Activity Report','',CURRENT_TIMESTAMP,'view_AccountActivityReport',1,2,'Reports>Productivity & Analysis',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Accounting','Allows a user to change closing dates for claims, payments and refunds; typically used by accountants for closing the books.',CURRENT_TIMESTAMP,'base_Accounting',1,1,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Adjustments Detail','',CURRENT_TIMESTAMP,'view_AdjustmentsDetail',1,2,'Reports>Payment Report',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Adjustments Summary','',CURRENT_TIMESTAMP,'view_AdjustmentsSummary',1,2,'Reports>Payment Report',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Appointment Detail','',CURRENT_TIMESTAMP,'view_AppointmentDetail',1,2,'Reports>Appointment',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Appointment Summary','',CURRENT_TIMESTAMP,'view_AppointmentSummary',1,2,'Reports>Appointment',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Appointments','Allows a user to complete appointment scheduling tasks such as accessing calendars, appointment details, resources and appointment reasons.',CURRENT_TIMESTAMP,'create_Appointments',1,3,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Appointments','Allows a user to complete appointment scheduling tasks such as accessing calendars, appointment details, resources and appointment reasons.',CURRENT_TIMESTAMP,'delete_Appointments',1,5,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Appointments','Allows a user to complete appointment scheduling tasks such as accessing calendars, appointment details, resources and appointment reasons.',CURRENT_TIMESTAMP,'edit_Appointments',1,4,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Appointments','Allows a user to complete appointment scheduling tasks such as accessing calendars, appointment details, resources and appointment reasons.',CURRENT_TIMESTAMP,'view_Appointments',1,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Audit log','Allows a user to view audit logs such as Encounter, User, Patient Record, Provider, Claim and Master Audit logs. Audit logs track key changes made to records by users within the system. ',CURRENT_TIMESTAMP,'view_Auditlog',1,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Business Rule','',CURRENT_TIMESTAMP,'create_BusinessRule',0,3,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Business Rule','',CURRENT_TIMESTAMP,'delete_BusinessRule',0,5,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Business Rule','',CURRENT_TIMESTAMP,'edit_BusinessRule',0,4,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Business Rule','',CURRENT_TIMESTAMP,'view_BusinessRule',0,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Charges Detail','',CURRENT_TIMESTAMP,'view_ChargesDetail',1,2,'Reports>Encounters',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Charges Export','',CURRENT_TIMESTAMP,'view_ChargesExport',1,2,'Reports>Encounters',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Charges Summary','',CURRENT_TIMESTAMP,'view_ChargesSummary',1,2,'Reports>Encounters',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Claims','Allows a user to view, create, edit and delete electronic & paper claims.',CURRENT_TIMESTAMP,'base_Claims',1,1,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Claims','Allows a user to view, create, edit and delete electronic & paper claims.',CURRENT_TIMESTAMP,'create_Claims',1,3,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Claims','Allows a user to view, create, edit and delete electronic & paper claims.',CURRENT_TIMESTAMP,'delete_Claims',1,5,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Claims','Allows a user to view, create, edit and delete electronic & paper claims.',CURRENT_TIMESTAMP,'edit_Claims',1,4,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Claims','Allows a user to view, create, edit and delete electronic & paper claims.',CURRENT_TIMESTAMP,'view_Claims',1,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Clearinghouse Report','Allows a user to view clearinghouse reports that are used to monitor and manage claim processing tasks, including claim rejections and posting payments.',CURRENT_TIMESTAMP,'base_ClearinghouseReport',1,1,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Clearinghouse Report','Allows a user to view clearinghouse reports that are used to monitor and manage claim processing tasks, including claim rejections and posting payments.',CURRENT_TIMESTAMP,'view_ClearinghouseReport',1,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Codes','Allows a user to view, create, edit and delete procedure charges and allowable rates.',CURRENT_TIMESTAMP,'create_Codes',1,3,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Codes','Allows a user to view, create, edit and delete procedure charges and allowable rates.',CURRENT_TIMESTAMP,'delete_Codes',1,5,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Codes','Allows a user to view, create, edit and delete procedure charges and allowable rates.',CURRENT_TIMESTAMP,'edit_Codes',1,4,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Codes','Allows a user to view, create, edit and delete procedure charges and allowable rates.',CURRENT_TIMESTAMP,'view_Codes',1,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Company Indicators Summary','',CURRENT_TIMESTAMP,'view_CompanyIndicatorsSummary',1,2,'Reports>Company',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Company User Productivity','',CURRENT_TIMESTAMP,'view_CompanyUserProductivity',1,2,'Reports>Company',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Contract Management Detail','',CURRENT_TIMESTAMP,'view_ContractManagementDetail',1,2,'Reports>Payment Report',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Contract Management Summary','',CURRENT_TIMESTAMP,'view_ContractManagementSummary',1,2,'Reports>Payment Report',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Contracts & Fees','Allows a user to view, create, edit and delete procedure charges and allowable rates.',CURRENT_TIMESTAMP,'create_ContractsAndFees',1,3,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Contracts & Fees','Allows a user to view, create, edit and delete procedure charges and allowable rates.',CURRENT_TIMESTAMP,'delete_ContractsAndFees',1,5,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Contracts & Fees','Allows a user to view, create, edit and delete procedure charges and allowable rates.',CURRENT_TIMESTAMP,'edit_ContractsAndFees',1,4,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Contracts & Fees','Allows a user to view, create, edit and delete procedure charges and allowable rates.',CURRENT_TIMESTAMP,'view_ContractsAndFees',1,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Customer','',CURRENT_TIMESTAMP,'create_Customer',0,3,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Customer','',CURRENT_TIMESTAMP,'delete_Customer',0,5,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Customer','',CURRENT_TIMESTAMP,'edit_Customer',0,4,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Customer','',CURRENT_TIMESTAMP,'view_Customer',0,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Customer Account Detail','',CURRENT_TIMESTAMP,'view_CustomerAccountDetail',1,2,'Reports>Company',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Customer Account Summary','',CURRENT_TIMESTAMP,'view_CustomerAccountSummary',1,2,'Reports>Company',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Daily Report','',CURRENT_TIMESTAMP,'view_DailyReport',1,2,'Reports>Productivity & Analysis',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Deactivate / Reactivate Permissions','',CURRENT_TIMESTAMP,'base_DeactivateReactivatePermissions',0,1,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Denials Detail','',CURRENT_TIMESTAMP,'view_DenialsDetail',1,2,'Reports>Payment Report',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Denials Summary','',CURRENT_TIMESTAMP,'view_DenialsSummary',1,2,'Reports>Payment Report',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('EHRs & API','Allows a user to connect to an external EHR system.',CURRENT_TIMESTAMP,'base_EHRsAndAPI',1,1,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('EHRs & API','Allows a user to connect to an external EHR system.',CURRENT_TIMESTAMP,'edit_EHRsAndAPI',1,4,'',0,NULL,1);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Encounter Details','',CURRENT_TIMESTAMP,'view_EncounterDetails',1,2,'Reports>Encounters',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Encounter Summary','',CURRENT_TIMESTAMP,'view_EncounterSummary',1,2,'Reports>Encounters',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Encounters','Allows a user to view, create, edit and delete encounters & encounter forms. To approve, un-approve or reject an encounter, a user must have Full Control.',CURRENT_TIMESTAMP,'base_Encounters',1,1,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Encounters','Allows a user to view, create, edit and delete encounters & encounter forms. To approve, un-approve or reject an encounter, a user must have Full Control.',CURRENT_TIMESTAMP,'create_Encounters',1,3,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Encounters','Allows a user to view, create, edit and delete encounters & encounter forms. To approve, un-approve or reject an encounter, a user must have Full Control.',CURRENT_TIMESTAMP,'delete_Encounters',1,5,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Encounters','Allows a user to view, create, edit and delete encounters & encounter forms. To approve, un-approve or reject an encounter, a user must have Full Control.',CURRENT_TIMESTAMP,'edit_Encounters',1,4,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Encounters','Allows a user to view, create, edit and delete encounters & encounter forms. To approve, un-approve or reject an encounter, a user must have Full Control.',CURRENT_TIMESTAMP,'view_Encounters',1,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Fax DMSBridge','',CURRENT_TIMESTAMP,'base_FaxDMSBridge',0,1,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Fee Schedule Detail','Allows a user to view, create, edit and delete procedure charges and allowable rates.',CURRENT_TIMESTAMP,'view_FeeScheduleDetail',1,2,'Reports>Settings',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Group Numbers','',CURRENT_TIMESTAMP,'view_GroupNumbers',1,2,'Reports>Settings',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('HL7 Integration','',CURRENT_TIMESTAMP,'edit_HL7Integration',0,4,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Insurance Authorization','',CURRENT_TIMESTAMP,'view_InsuranceAuthorization',1,2,'Reports>Patient',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Insurance Collections Detail','',CURRENT_TIMESTAMP,'view_InsuranceCollectionsDetail',1,2,'Reports>Accounts Recievable',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Insurance Collections Summary','',CURRENT_TIMESTAMP,'view_InsuranceCollectionsSummary',1,2,'Reports>Accounts Recievable',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Insurance Companies & Plans','Allows a user to view, create, edit and delete insurance companies, insurance plans and payer scenarios. ',CURRENT_TIMESTAMP,'create_InsuranceCompaniesAndPlans',1,3,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Insurance Companies & Plans','Allows a user to view, create, edit and delete insurance companies, insurance plans and payer scenarios. ',CURRENT_TIMESTAMP,'delete_InsuranceCompaniesAndPlans',1,5,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Insurance Companies & Plans','Allows a user to view, create, edit and delete insurance companies, insurance plans and payer scenarios. ',CURRENT_TIMESTAMP,'edit_InsuranceCompaniesAndPlans',1,4,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Insurance Companies & Plans','Allows a user to view, create, edit and delete insurance companies, insurance plans and payer scenarios. ',CURRENT_TIMESTAMP,'view_InsuranceCompaniesAndPlans',1,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Itemization Of Charges','',CURRENT_TIMESTAMP,'view_ItemizationOfCharges',1,2,'Reports>Patient',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Kareo Sign In','',CURRENT_TIMESTAMP,'base_KareoSignIn',0,1,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Key Indicators D.R.O. Analysis','',CURRENT_TIMESTAMP,'view_KeyIndicatorsDROAnalysis',1,2,'Reports>Key Indicators',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Key Indicators Detail','',CURRENT_TIMESTAMP,'view_KeyIndicatorsDetail',1,2,'Reports>Key Indicators',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Key Indicators Summary','',CURRENT_TIMESTAMP,'view_KeyIndicatorsSummary',1,2,'Reports>Key Indicators',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Key Indicators Summary Compare Previous Year','',CURRENT_TIMESTAMP,'view_KeyIndicatorsSummaryComparePreviousYear',1,2,'Reports>Key Indicators',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Kfax','Allows a user to create and delete kfax numbers for a practice.',CURRENT_TIMESTAMP,'base_Kfax',1,1,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Manage Documents','“Users with this permission are able to upload and manage documents that might be related to a patient or an encounter.”',CURRENT_TIMESTAMP,'base_ManageDocuments',1,1,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Manage User Accounts','Allows a user to view, create, edit and delete user accounts for staff who need to access the system.',CURRENT_TIMESTAMP,'base_ManageUserAccounts',1,1,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Missed Copays','',CURRENT_TIMESTAMP,'view_MissedCopays',1,2,'Reports>Payment Report',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Missed Encounters','',CURRENT_TIMESTAMP,'view_MissedEncounters',1,2,'Reports>Encounters',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Missing Document','',CURRENT_TIMESTAMP,'view_MissingDocument',1,2,'Reports>Documents',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Old Reports','',CURRENT_TIMESTAMP,'view_OldReports',0,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patient','Allows a user to view, create, edit and delete patient records and information: Patient, employer, workers comp offices, eligibility, attorneys, journal notes, collection categories and referral sources.',CURRENT_TIMESTAMP,'create_Patient',1,3,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patient','Allows a user to view, create, edit and delete patient records and information: Patient, employer, workers comp offices, eligibility, attorneys, journal notes, collection categories and referral sources.',CURRENT_TIMESTAMP,'delete_Patient',1,5,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patient','Allows a user to view, create, edit and delete patient records and information: Patient, employer, workers comp offices, eligibility, attorneys, journal notes, collection categories and referral sources.',CURRENT_TIMESTAMP,'edit_Patient',1,4,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patient','Allows a user to view, create, edit and delete patient records and information: Patient, employer, workers comp offices, eligibility, attorneys, journal notes, collection categories and referral sources.',CURRENT_TIMESTAMP,'view_Patient',1,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patient Balance Detail','',CURRENT_TIMESTAMP,'view_PatientBalanceDetail',1,2,'Reports>Patient',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patient Balance Summary','',CURRENT_TIMESTAMP,'view_PatientBalanceSummary',1,2,'Reports>Patient',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patient Collections Detail','',CURRENT_TIMESTAMP,'view_PatientCollectionsDetail',1,2,'Reports>Accounts Recievable',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patient Collections Summary','',CURRENT_TIMESTAMP,'view_PatientCollectionsSummary',1,2,'Reports>Accounts Recievable',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patient Contact List','',CURRENT_TIMESTAMP,'view_PatientContactList',1,2,'Reports>Patient',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patient Demographic Export','',CURRENT_TIMESTAMP,'view_PatientDemographicExport',1,2,'Reports>Patient',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patient Detail','',CURRENT_TIMESTAMP,'view_PatientDetail',1,2,'Reports>Patient',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patient Financial History','',CURRENT_TIMESTAMP,'view_PatientFinancialHistory',1,2,'Reports>Patient',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patient History','',CURRENT_TIMESTAMP,'view_PatientHistory',1,2,'Reports>Patient',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patient Referral Detail','',CURRENT_TIMESTAMP,'view_PatientReferralDetail',1,2,'Reports>Patient',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patient Referral Summary','',CURRENT_TIMESTAMP,'view_PatientReferralSummary',1,2,'Reports>Patient',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patient Statement','',CURRENT_TIMESTAMP,'view_PatientStatement',1,2,'Reports>Patient',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patient Statements','Allows a user to manage statements sent out to patients.',CURRENT_TIMESTAMP,'create_PatientStatements',1,3,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patient Statements','Allows a user to manage statements sent out to patients.',CURRENT_TIMESTAMP,'edit_PatientStatements',1,4,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patient Statements','Allows a user to manage statements sent out to patients.',CURRENT_TIMESTAMP,'view_PatientStatements',1,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patient Transaction Detail','',CURRENT_TIMESTAMP,'view_PatientTransactionDetail',1,2,'Reports>Patient',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patient Transaction Summary','',CURRENT_TIMESTAMP,'view_PatientTransactionSummary',1,2,'Reports>Patient',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Patients Summary','',CURRENT_TIMESTAMP,'view_PatientsSummary',1,2,'Reports>Patient',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Payer Mix Summary','',CURRENT_TIMESTAMP,'view_PayerMixSummary',1,2,'Reports>Payment Report',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Payment Application','',CURRENT_TIMESTAMP,'view_PaymentApplication',1,2,'Reports>Payment Report',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Payment Receipt','',CURRENT_TIMESTAMP,'view_PaymentReceipt',1,2,'Reports>Payment Report',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Payments','Allows a user to manage capitated accounts and patient payments. To authorize credit cards and electronic checks, a user must have Full Control.',CURRENT_TIMESTAMP,'base_Payments',1,1,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Payments','Allows a user to manage capitated accounts and patient payments. To authorize credit cards and electronic checks, a user must have Full Control.',CURRENT_TIMESTAMP,'create_Payments',1,3,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Payments','Allows a user to manage capitated accounts and patient payments. To authorize credit cards and electronic checks, a user must have Full Control.',CURRENT_TIMESTAMP,'delete_Payments',1,5,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Payments','Allows a user to manage capitated accounts and patient payments. To authorize credit cards and electronic checks, a user must have Full Control.',CURRENT_TIMESTAMP,'edit_Payments',1,4,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Payments','Allows a user to manage capitated accounts and patient payments. To authorize credit cards and electronic checks, a user must have Full Control.',CURRENT_TIMESTAMP,'view_Payments',1,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Payments & Refunds','Allows a user to view, create, edit and delete refunds.',CURRENT_TIMESTAMP,'create_PaymentsAndRefunds',1,3,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Payments & Refunds','Allows a user to view, create, edit and delete refunds.',CURRENT_TIMESTAMP,'delete_PaymentsAndRefunds',1,5,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Payments & Refunds','Allows a user to view, create, edit and delete refunds.',CURRENT_TIMESTAMP,'edit_PaymentsAndRefunds',1,4,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Payments & Refunds','Allows a user to view, create, edit and delete refunds.',CURRENT_TIMESTAMP,'view_PaymentsAndRefunds',1,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Payments Application','',CURRENT_TIMESTAMP,'view_PaymentsApplication',1,2,'Reports>Payment Report',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Payments by Procedure','',CURRENT_TIMESTAMP,'view_PaymentsbyProcedure',1,2,'Reports>Payment Report',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Payments Detail','',CURRENT_TIMESTAMP,'view_PaymentsDetail',1,2,'Reports>Payment Report',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Payments Summary','',CURRENT_TIMESTAMP,'view_PaymentsSummary',1,2,'Reports>Payment Report',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Practice Settings','Allows a user to set up and manage practice settings: Group numbers, providers, service locations,  collection categories, encounter layouts and encounter forms. This permission is necessary for all application administrators.',CURRENT_TIMESTAMP,'base_PracticeSettings',1,1,'',0,NULL,1);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Practice Settings','Allows a user to set up and manage practice settings: Group numbers, providers, service locations,  collection categories, encounter layouts and encounter forms. This permission is necessary for all application administrators.',CURRENT_TIMESTAMP,'create_PracticeSettings',1,3,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Practice Settings','Allows a user to set up and manage practice settings: Group numbers, providers, service locations,  collection categories, encounter layouts and encounter forms. This permission is necessary for all application administrators.',CURRENT_TIMESTAMP,'delete_PracticeSettings',1,5,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Practice Settings','Allows a user to set up and manage practice settings: Group numbers, providers, service locations,  collection categories, encounter layouts and encounter forms. This permission is necessary for all application administrators.',CURRENT_TIMESTAMP,'edit_PracticeSettings',1,4,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Practice Settings','Allows a user to set up and manage practice settings: Group numbers, providers, service locations,  collection categories, encounter layouts and encounter forms. This permission is necessary for all application administrators.',CURRENT_TIMESTAMP,'view_PracticeSettings',1,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Procedure Macro','',CURRENT_TIMESTAMP,'create_ProcedureMacro',1,3,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Procedure Macro','',CURRENT_TIMESTAMP,'delete_ProcedureMacro',1,5,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Procedure Macro','',CURRENT_TIMESTAMP,'edit_ProcedureMacro',1,4,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Procedure Macro','',CURRENT_TIMESTAMP,'view_ProcedureMacro',1,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Procedure Payments','',CURRENT_TIMESTAMP,'view_ProcedurePayments',1,2,'Reports>Productivity & Analysis',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Provider Numbers','',CURRENT_TIMESTAMP,'view_ProviderNumbers',1,2,'Reports>Settings',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Provider productivity report','',CURRENT_TIMESTAMP,'view_Providerproductivityreport',1,2,'Reports>Productivity & Analysis',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Provider Utilization','',CURRENT_TIMESTAMP,'view_ProviderUtilization',1,2,'Reports>Appointment',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Providers','Allows a user to view, create, edit and delete provider records.',CURRENT_TIMESTAMP,'edit_Providers',1,4,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Providers','Allows a user to view, create, edit and delete provider records.',CURRENT_TIMESTAMP,'view_Providers',1,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Referring Physicians','Allows a user to view, create, edit and delete referring physician records.',CURRENT_TIMESTAMP,'create_ReferringPhysicians',1,3,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Referring Physicians','Allows a user to view, create, edit and delete referring physician records.',CURRENT_TIMESTAMP,'delete_ReferringPhysicians',1,5,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Referring Physicians','Allows a user to view, create, edit and delete referring physician records.',CURRENT_TIMESTAMP,'edit_ReferringPhysicians',1,4,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Referring Physicians','Allows a user to view, create, edit and delete referring physician records.',CURRENT_TIMESTAMP,'view_ReferringPhysicians',1,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Refund Detail','',CURRENT_TIMESTAMP,'view_RefundDetail',1,2,'Reports>Refunds',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Refund Summary','',CURRENT_TIMESTAMP,'view_RefundSummary',1,2,'Reports>Refunds',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Remote Desktop Assistance','',CURRENT_TIMESTAMP,'view_RemoteDesktopAssistance',0,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Reports Closing Date','',CURRENT_TIMESTAMP,'edit_ReportsClosingDate',1,4,'Reports',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Service Locations','',CURRENT_TIMESTAMP,'view_ServiceLocations',1,2,'Reports>Settings',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Service Manager','',CURRENT_TIMESTAMP,'base_ServiceManager',0,1,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Settled Charges Summary','',CURRENT_TIMESTAMP,'view_SettledChargesSummary',1,2,'Reports>Encounters',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Subscription Edition','',CURRENT_TIMESTAMP,'create_SubscriptionEdition',0,3,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Subscription Edition','',CURRENT_TIMESTAMP,'delete_SubscriptionEdition',0,5,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Subscription Edition','',CURRENT_TIMESTAMP,'edit_SubscriptionEdition',0,4,'',0,NULL,1);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Subscription Edition','',CURRENT_TIMESTAMP,'view_SubscriptionEdition',0,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Tasks','Allows a user to view, create, attach, edit and delete tasks.',CURRENT_TIMESTAMP,'create_Tasks',1,3,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Tasks','Allows a user to view, create, attach, edit and delete tasks.',CURRENT_TIMESTAMP,'delete_Tasks',1,5,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Tasks','Allows a user to view, create, attach, edit and delete tasks.',CURRENT_TIMESTAMP,'edit_Tasks',1,4,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Tasks','Allows a user to view, create, attach, edit and delete tasks.',CURRENT_TIMESTAMP,'view_Tasks',1,2,'',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Unapplied Analysis','',CURRENT_TIMESTAMP,'view_UnappliedAnalysis',1,2,'Reports>Payment Report',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Unpaid Insurance Claims','',CURRENT_TIMESTAMP,'view_UnpaidInsuranceClaims',1,2,'Reports>Accounts Recievable',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Unpaid Insurance Claims Export','',CURRENT_TIMESTAMP,'view_UnpaidInsuranceClaimsExport',1,2,'Reports>Accounts Recievable',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Unscheduled Analysis','',CURRENT_TIMESTAMP,'view_UnscheduledAnalysis',1,2,'Reports>Appointment',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('User Productivity Report','',CURRENT_TIMESTAMP,'view_UserProductivityReport',1,2,'Reports>Productivity & Analysis',0,NULL,0);
INSERT INTO [UserAccount_Permissions] ([Name], [Description], [CreatedDate], [PermissionValue], [ViewInKareo], [PermissionType], [HierarchyInfo], [Deleted], [DateDeleted],[QuestUserDenied])  VALUES ('Visible On Dashboard','',CURRENT_TIMESTAMP,'view_VisibleOnDashboard',1,2,'Reports>Key Indicators',0,NULL,0);

GO
