IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EncounterProcedure' AND COLUMN_NAME = 'StartTimeText')
	ALTER TABLE dbo.EncounterProcedure
	ADD StartTimeText VARCHAR(4)

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EncounterProcedure' AND COLUMN_NAME = 'EndTimeText')
	ALTER TABLE dbo.EncounterProcedure
	ADD EndTimeText VARCHAR(4)