IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.Columns WHERE column_name='Ethnicity' AND COLUMNS.TABLE_NAME='Patient')
BEGIN
	ALTER TABLE dbo.Patient
	ADD Ethnicity VARCHAR(64) NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.Columns WHERE column_name='Race' AND COLUMNS.TABLE_NAME='Patient')
BEGIN
	ALTER TABLE dbo.Patient
	ADD Race VARCHAR(64) NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.Columns WHERE column_name='LicenseNumber' AND COLUMNS.TABLE_NAME='Patient')
BEGIN
	ALTER TABLE dbo.Patient
	ADD LicenseNumber VARCHAR(64) NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.Columns WHERE column_name='LicenseState' AND COLUMNS.TABLE_NAME='Patient')
BEGIN
	ALTER TABLE dbo.Patient
	ADD LicenseState VARCHAR(2) NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.Columns WHERE column_name='Language1' AND COLUMNS.TABLE_NAME='Patient')
BEGIN
	ALTER TABLE dbo.Patient
	ADD Language1 VARCHAR(64) NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.Columns WHERE column_name='Language2' AND COLUMNS.TABLE_NAME='Patient')
BEGIN
	ALTER TABLE dbo.Patient
	ADD Language2 VARCHAR(64) NULL
END